development:
  adapter:  postgresql
  encoding: unicode
  database: photo_show
  username: photo_show
  password: photo_show
  pool: 5
  timeout: 5000

production:
  adapter:  postgresql
  encoding: unicode
  database: photo_show
  username: photo_show
  password: photo_show
  pool: 5
  timeout: 5000